import { SecurityRule, SecuritySeverity, SecurityCategory, RuleType } from '../types';

export const apiSecurityRules: SecurityRule[] = [
  {
    code: 'API001',
    message: 'Reminder: Ensure authentication middleware is applied to API endpoints',
    severity: SecuritySeverity.Warning,
    patterns: [
      /app\.(?:get|post|put|delete|patch)\s*\(\s*['"]\/api\//i,
      /router\.(?:get|post|put|delete|patch)\s*\(\s*['"]\/api\//i,
    ],
    suggestion: 'Apply authentication middleware to API endpoints (e.g., app.get("/api/data", authMiddleware, handler))',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'API002',
    message: 'GraphQL introspection may be enabled in production',
    severity: SecuritySeverity.Warning,
    patterns: [
      /introspection\s*:\s*true/i,
    ],
    suggestion: 'Disable GraphQL introspection in production to prevent schema disclosure',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'API003',
    message: 'Reminder: Apply rate limiting to API routes',
    severity: SecuritySeverity.Info,
    patterns: [
      /app\.use\s*\(\s*['"]\/api/i,
    ],
    suggestion: 'Apply rate limiting middleware to API routes to prevent abuse and DDoS',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'API004',
    message: 'Verbose error details exposed to client',
    severity: SecuritySeverity.Warning,
    patterns: [
      /res\.(?:json|send)\s*\(.*(?:stack|stackTrace)/i,
      /\.status\s*\(\s*500\s*\)\.(?:json|send)\s*\(\s*(?:err|error)\s*\)/i,
    ],
    suggestion: 'Return generic error messages to clients; log detailed errors server-side only',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'API005',
    message: 'Missing request body size limit',
    severity: SecuritySeverity.Warning,
    patterns: [
      /express\.json\s*\(\s*\)/,
      /bodyParser\.json\s*\(\s*\)/,
    ],
    suggestion: 'Set body size limits: express.json({ limit: "10kb" }) to prevent DoS via large payloads',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'API006',
    message: 'Debug or development mode enabled',
    severity: SecuritySeverity.Warning,
    patterns: [
      /DEBUG\s*[:=]\s*(?:true|1|['"]true['"])/i,
      /app\.debug\s*=\s*True/i,
      /FLASK_DEBUG\s*[:=]\s*1/i,
    ],
    suggestion: 'Ensure debug mode is disabled in production environments',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'API007',
    message: 'Error stack trace exposed',
    severity: SecuritySeverity.Warning,
    patterns: [
      /(?:err|error)\.stack/i,
    ],
    suggestion: 'Do not send stack traces to clients; log them server-side for debugging',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'API008',
    message: 'Reminder: Validate API keys/tokens before processing requests',
    severity: SecuritySeverity.Info,
    patterns: [
      /api[_-]?key/i,
      /apiToken/i,
      /x-api-key/i,
    ],
    suggestion: 'Verify API keys/tokens are valid, not revoked, and have appropriate scopes before processing any request',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'API009',
    message: 'Reminder: Ensure API keys have expiration dates and are rotatable',
    severity: SecuritySeverity.Info,
    patterns: [
      /(?:generate|create|issue).*(?:api[_-]?key|token)/i,
      /(?:api[_-]?key|token).*(?:generate|create|issue)/i,
    ],
    suggestion: 'Set expiration dates on API keys; provide a key rotation mechanism so users can rotate keys without downtime',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'API010',
    message: 'Possible IDOR: resource accessed by user-supplied ID without authorization check',
    severity: SecuritySeverity.Warning,
    patterns: [
      /(?:params|query)\.(?:id|userId|user_id|accountId|account_id)\b/i,
      /findById\s*\(\s*(?:req|request)\./i,
      /findOne\s*\(\s*\{\s*(?:_id|id)\s*:\s*(?:req|request)\./i,
    ],
    suggestion: 'Always verify the authenticated user owns or has permission to access the requested resource (prevent IDOR)',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'API011',
    message: 'Overly permissive or wildcard permissions detected',
    severity: SecuritySeverity.Warning,
    patterns: [
      /role\s*[:=]\s*['"]\*['"]/i,
      /permissions?\s*[:=]\s*\[\s*['"]\*['"]\s*\]/i,
      /scope\s*[:=]\s*['"]\*['"]/i,
      /allow\s*[:=]\s*['"]\*['"]/i,
    ],
    suggestion: 'Use least-privilege permissions; define specific scopes and roles instead of wildcards',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'API012',
    message: 'Reminder: Configure burst limits and rate limit headers',
    severity: SecuritySeverity.Info,
    patterns: [
      /rateLimit/i,
      /rateLimiter/i,
      /express-rate-limit/i,
    ],
    suggestion: 'Set burst limits alongside sustained rate limits; return X-RateLimit-Limit/Remaining/Reset headers to clients',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'API013',
    message: 'Reminder: Differentiate rate limits for authenticated vs anonymous users',
    severity: SecuritySeverity.Info,
    patterns: [
      /windowMs/i,
      /max\s*:\s*\d+.*(?:request|req)/i,
    ],
    suggestion: 'Apply stricter rate limits for unauthenticated requests; allow higher limits for verified authenticated users',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'API014',
    message: 'Reminder: Ensure DDoS protection is in place',
    severity: SecuritySeverity.Info,
    patterns: [
      /app\.listen\s*\(/i,
      /createServer\s*\(/i,
    ],
    suggestion: 'Deploy DDoS protection (e.g., CDN, WAF, cloud provider DDoS shield) in front of your API',
    category: SecurityCategory.APISecurity,
    ruleType: RuleType.Informational,
  },
];
