import { SecurityRule, SecuritySeverity, SecurityCategory, RuleType } from '../types';

export const databaseRules: SecurityRule[] = [
  {
    code: 'DB001',
    message: 'Potential SQL injection via string concatenation',
    severity: SecuritySeverity.Error,
    patterns: [
      /(?:\.query|\.exec|\.prepare|\.execute|\.raw)\s*\(\s*['"`].*\b(?:SELECT|INSERT|UPDATE|DELETE|DROP|ALTER)\b.*['"`]\s*\+/i,
      /(?:\.query|\.exec|\.prepare|\.execute|\.raw)\s*\(\s*`.*\b(?:SELECT|INSERT|UPDATE|DELETE|DROP|ALTER)\b.*\$\{/i,
      /['"`]\s*\+\s*(?:req|request|params|query|body)\./i,
      /\.query\s*\(\s*['"`].*\+/i,
    ],
    negativePatterns: [
      /confirm\s*\(/i,
      /alert\s*\(/i,
      /localStorage/i,
      /sessionStorage/i,
      /console\.\w+\s*\(/i,
      /window\.\w+/i,
    ],
    suggestion: 'Use parameterized queries or prepared statements; never concatenate user input into SQL',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.CodeDetectable,
    contextAware: true,
  },
  {
    code: 'DB002',
    message: 'NoSQL injection: unsanitized user input in query object',
    severity: SecuritySeverity.Error,
    patterns: [
      /\.find\s*\(\s*(?:req|request)\.(?:body|query|params)/i,
      /\.findOne\s*\(\s*(?:req|request)\.(?:body|query|params)/i,
      /\$where\s*:/i,
    ],
    suggestion: 'Validate and sanitize inputs before using in MongoDB/NoSQL queries; avoid $where operator',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'DB003',
    message: 'Database connection string with embedded credentials',
    severity: SecuritySeverity.Error,
    patterns: [
      /(?:mongodb|mysql|postgres|postgresql|mssql):\/\/\w+:\w+@/i,
      /connectionString\s*[:=]\s*['"].*(?:password|pwd)\s*=/i,
    ],
    suggestion: 'Store database connection strings in environment variables or a secrets manager',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'DB004',
    message: 'ORM raw query with potential injection',
    severity: SecuritySeverity.Warning,
    patterns: [
      /\.raw\s*\(\s*['"`].*\+/i,
      /\.raw\s*\(\s*`.*\$\{/i,
      /Sequelize\.literal\s*\(/i,
      /\.execute\s*\(\s*f['"].*\{/i,
    ],
    suggestion: 'Use parameterized ORM queries; pass user input as bind parameters to raw queries',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'DB005',
    message: 'Command injection in system/exec call',
    severity: SecuritySeverity.Error,
    patterns: [
      /child_process.*exec\s*\(.*\+/i,
      /child_process.*exec\s*\(.*\$\{/i,
      /os\.system\s*\(.*\+/i,
      /subprocess\.call\s*\(.*shell\s*=\s*True/i,
    ],
    suggestion: 'Use parameterized process spawning; avoid passing user input to shell commands',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'DB006',
    message: 'SELECT * may over-fetch sensitive columns',
    severity: SecuritySeverity.Info,
    patterns: [
      /SELECT\s+\*\s+FROM/i,
    ],
    suggestion: 'Select only needed columns to avoid accidentally exposing sensitive fields',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'DB007',
    message: 'Reminder: Review destructive SQL operations carefully',
    severity: SecuritySeverity.Info,
    patterns: [
      /DROP\s+TABLE/i,
      /DROP\s+DATABASE/i,
      /TRUNCATE\s+TABLE/i,
    ],
    suggestion: 'Ensure backups exist before running destructive SQL migrations',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'DB008',
    message: 'Reminder: Ensure database user has least-privilege access',
    severity: SecuritySeverity.Info,
    patterns: [
      /GRANT\s+ALL/i,
      /createConnection/i,
      /createPool/i,
      /mongoose\.connect/i,
    ],
    suggestion: 'Use a dedicated database user with minimal permissions (no GRANT ALL); separate read-only and read-write users',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'DB009',
    message: 'Reminder: Test database backups regularly',
    severity: SecuritySeverity.Info,
    patterns: [
      /(?:backup|dump|restore).*(?:database|db|sql|mongo)/i,
      /(?:database|db|sql|mongo).*(?:backup|dump|restore)/i,
    ],
    suggestion: 'Regularly test backup restoration to ensure backups are valid and recovery procedures work',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'DB010',
    message: 'Reminder: Enable database access logging and auditing',
    severity: SecuritySeverity.Info,
    patterns: [
      /\.query\s*\(/i,
      /\.execute\s*\(/i,
    ],
    suggestion: 'Enable database query logging and auditing to detect unauthorized access and track data modifications',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.Informational,
  },
  {
    code: 'DB011',
    message: 'Possible default or common database credentials',
    severity: SecuritySeverity.Error,
    patterns: [
      /(?:user|username)\s*[:=]\s*['"](?:root|admin|sa|postgres|mysql)['"]/i,
      /(?:password|passwd|pwd)\s*[:=]\s*['"](?:root|admin|password|123456|)['"]/i,
    ],
    suggestion: 'Change default database credentials immediately; use strong, unique passwords managed via secrets manager',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'DB012',
    message: 'Reminder: Restrict database network access to application servers only',
    severity: SecuritySeverity.Info,
    patterns: [
      /(?:host|hostname)\s*[:=]\s*['"](?:0\.0\.0\.0|localhost|127\.0\.0\.1)['"]/i,
    ],
    suggestion: 'Configure firewall rules to restrict database access to application servers only; never expose databases to the public internet',
    category: SecurityCategory.DatabaseSecurity,
    ruleType: RuleType.Informational,
  },
];
