import { SecurityRule, SecuritySeverity, SecurityCategory, RuleType } from '../types';

export const encryptionRules: SecurityRule[] = [
  {
    code: 'ENC001',
    message: 'Weak or deprecated cryptographic algorithm',
    severity: SecuritySeverity.Error,
    patterns: [
      /createCipher\s*\(/,
      /['"]md5['"]/i,
      /['"]sha1['"]/i,
      /['"]des['"]/i,
      /['"]rc4['"]/i,
      /MessageDigest\.getInstance\s*\(\s*['"](?:MD5|SHA-?1)['"]/i,
      /hashlib\.(?:md5|sha1)\s*\(/i,
    ],
    suggestion: 'Use SHA-256 or stronger; use bcrypt/argon2/PBKDF2 for passwords; use AES-256-GCM for encryption',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'ENC002',
    message: 'Hardcoded encryption key or initialization vector',
    severity: SecuritySeverity.Error,
    patterns: [
      /(?:encryption|cipher|aes|crypto)[_\s]*(?:key|iv|nonce)\s*[:=]\s*['"][^'"]+['"]/i,
      /createCipheriv\s*\(\s*['"][^'"]+['"],\s*['"][^'"]+['"]/i,
    ],
    suggestion: 'Use secure key management (KMS, vault, env vars); never hardcode encryption keys',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'ENC003',
    message: 'HTTP used instead of HTTPS for external URL',
    severity: SecuritySeverity.Warning,
    patterns: [
      /['"]http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0)/i,
    ],
    suggestion: 'Use HTTPS for all external communications to prevent MITM attacks',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'ENC004',
    message: 'TLS/SSL certificate verification disabled',
    severity: SecuritySeverity.Error,
    patterns: [
      /rejectUnauthorized\s*:\s*false/i,
      /InsecureSkipVerify\s*:\s*true/i,
      /ssl_verify\s*[:=]\s*false/i,
      /NODE_TLS_REJECT_UNAUTHORIZED.*['"]0['"]/,
      /CERT_NONE/,
    ],
    suggestion: 'Never disable TLS certificate verification in production',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'ENC005',
    message: 'Weak random number generation for security purpose',
    severity: SecuritySeverity.Warning,
    patterns: [
      /Math\.random\s*\(/,
    ],
    negativePatterns: [
      /(?:id|key|index|seed|color|opacity|position|width|height|left|top|zIndex|order|delay|duration)\s*[:=]/i,
      /className/i,
      /style\s*[:=]/i,
      /animation/i,
      /Math\.random\s*\(\s*\)\s*\.\s*toString/i,
    ],
    suggestion: 'Use crypto.randomBytes(), crypto.randomUUID(), or secrets module for security-sensitive randomness',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'ENC006',
    message: 'ECB mode detected (insecure block cipher mode)',
    severity: SecuritySeverity.Error,
    patterns: [
      /['"](?:aes|des).*ecb['"]/i,
      /MODE_ECB/,
    ],
    suggestion: 'Use GCM or CBC mode with proper IV; ECB mode leaks patterns in encrypted data',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'ENC007',
    message: 'Sensitive data logged or printed',
    severity: SecuritySeverity.Warning,
    patterns: [
      /console\.log\s*\(.*(?:password|secret|token|credential|ssn|credit.?card)/i,
      /print\s*\(.*(?:password|secret|token|credential)/i,
      /logger\.(?:info|debug|warn|error)\s*\(.*(?:password|secret|token)/i,
    ],
    suggestion: 'Never log sensitive data; mask or redact secrets before logging',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'ENC008',
    message: 'Reminder: Ensure PII and sensitive fields are encrypted at rest',
    severity: SecuritySeverity.Info,
    patterns: [
      /\b(?:ssn|social_security|credit.?card|date.?of.?birth|passport)\b/i,
    ],
    negativePatterns: [
      /className/i,
      /class\s*=/i,
      /classList/i,
      /css/i,
      /style/i,
    ],
    suggestion: 'Encrypt sensitive PII fields at rest using application-level encryption or database encryption',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.Informational,
    contextAware: true,
  },
  {
    code: 'ENC009',
    message: 'Missing or misconfigured HSTS header',
    severity: SecuritySeverity.Warning,
    patterns: [
      /Strict-Transport-Security/i,
    ],
    suggestion: 'Set Strict-Transport-Security header with max-age of at least 31536000 (1 year) and include includeSubDomains',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.Informational,
  },
  {
    code: 'ENC010',
    message: 'PII field logged without masking',
    severity: SecuritySeverity.Warning,
    patterns: [
      /(?:console\.log|logger\.\w+|print)\s*\(.*(?:email|phone|address|name|dob|birth)/i,
    ],
    suggestion: 'Mask PII in logs (e.g., show only last 4 digits); never log full PII values',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'ENC011',
    message: 'Reminder: Ensure database backups are encrypted',
    severity: SecuritySeverity.Info,
    patterns: [
      /(?:backup|dump|export).*(?:database|db|sql|mongo)/i,
      /(?:database|db|sql|mongo).*(?:backup|dump|export)/i,
    ],
    suggestion: 'Encrypt all database backups at rest; use encrypted storage for backup files',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.ProjectAdvisory,
  },
  {
    code: 'ENC012',
    message: 'Reminder: Ensure GDPR data export and deletion capabilities',
    severity: SecuritySeverity.Info,
    patterns: [
      /(?:userData|userProfile|personalData|userRecord)/i,
      /(?:gdpr|data.?subject|right.?to.?erasure|data.?portability)/i,
    ],
    suggestion: 'Implement user data export (GDPR Art. 20) and deletion on request (GDPR Art. 17); ensure all related records are purged',
    category: SecurityCategory.EncryptionDataProtection,
    ruleType: RuleType.ProjectAdvisory,
  },
];
