import { SecurityRule, SecuritySeverity, SecurityCategory, RuleType } from '../types';

export const fileHandlingRules: SecurityRule[] = [
  {
    code: 'FILE001',
    message: 'Potential path traversal: user input in file path',
    severity: SecuritySeverity.Error,
    patterns: [
      /(?:readFile|readFileSync|createReadStream)\s*\(.*(?:req|request|params|query|body)\./i,
      /open\s*\(.*(?:req|request|params|query)\./i,
    ],
    suggestion: 'Validate and sanitize file paths; use path.resolve() and verify the result is within an allowed directory',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'FILE002',
    message: 'Reminder: Validate file uploads for type, size, and content',
    severity: SecuritySeverity.Warning,
    patterns: [
      /upload\.(?:single|array|fields)\s*\(/,
      /multer\s*\(/,
    ],
    suggestion: 'Validate file type (whitelist extensions/MIME), enforce size limits, and scan for malicious content',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.Informational,
  },
  {
    code: 'FILE003',
    message: 'Temporary file with potentially insecure permissions',
    severity: SecuritySeverity.Warning,
    patterns: [
      /writeFileSync\s*\(\s*['"]\/tmp\//i,
      /tempfile\./i,
      /os\.CreateTemp/i,
    ],
    suggestion: 'Use secure temp file creation with restricted permissions (0600); clean up temp files after use',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'FILE004',
    message: 'Symlink following may lead to path traversal',
    severity: SecuritySeverity.Warning,
    patterns: [
      /followSymlinks\s*:\s*true/i,
    ],
    suggestion: 'Avoid following symlinks for user-supplied paths; use lstat to check before opening',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'FILE005',
    message: 'World-writable file permissions',
    severity: SecuritySeverity.Warning,
    patterns: [
      /0o?777/,
      /0o?766/,
      /0o?776/,
    ],
    suggestion: 'Use restrictive file permissions (e.g., 0644 or 0600); avoid world-writable files',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'FILE006',
    message: 'File path constructed from user input without sanitization',
    severity: SecuritySeverity.Error,
    patterns: [
      /path\.join\s*\(.*(?:req|request|params|query|body)\./i,
      /path\.resolve\s*\(.*(?:req|request|params|query|body)\./i,
    ],
    suggestion: 'Sanitize and validate file paths; reject paths containing ".." or absolute paths from user input',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'FILE007',
    message: 'Reminder: Store uploaded files outside the web root',
    severity: SecuritySeverity.Info,
    patterns: [
      /upload.*(?:public|static|www|htdocs|webroot)/i,
      /destination\s*:\s*['"].*(?:public|static)/i,
    ],
    suggestion: 'Store uploaded files outside the document root and serve through a controller with access checks',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.Informational,
  },
  {
    code: 'FILE008',
    message: 'File upload detected without virus/malware scanning',
    severity: SecuritySeverity.Warning,
    patterns: [
      /\.originalname/i,
      /req\.file\b/i,
      /req\.files\b/i,
    ],
    suggestion: 'Scan uploaded files for viruses/malware before storing (e.g., ClamAV, VirusTotal API)',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.Informational,
  },
  {
    code: 'FILE009',
    message: 'Cloud storage bucket may be publicly accessible',
    severity: SecuritySeverity.Error,
    patterns: [
      /(?:acl|ACL)\s*[:=]\s*['"]public-read['"]/i,
      /PublicRead/,
      /allUsers.*(?:storage|bucket|iam|role|binding|permission|acl)/i,
      /(?:storage|bucket|iam|role|binding|permission|acl).*allUsers/i,
      /public\s*:\s*true.*(?:bucket|storage|blob)/i,
    ],
    negativePatterns: [
      /<Select/i,
      /<Option/i,
      /SelectItem/i,
      /MenuItem/i,
      /value\s*=\s*["']/i,
      /label\s*=\s*["']/i,
    ],
    suggestion: 'Set storage buckets to private by default; use signed URLs or IAM policies for controlled access',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'FILE010',
    message: 'Reminder: Serve public files through signed/pre-signed URLs',
    severity: SecuritySeverity.Info,
    patterns: [
      /getSignedUrl/i,
      /presigned/i,
      /generateSignedUrl/i,
      /s3\.getObject/i,
    ],
    suggestion: 'Use time-limited signed URLs to serve files; never expose raw bucket URLs publicly',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.Informational,
  },
  {
    code: 'FILE011',
    message: 'Reminder: Ensure storage rules restrict access to authenticated users with ownership checks',
    severity: SecuritySeverity.Info,
    patterns: [
      /storage\.rules/i,
      /firebaseStorage/i,
      /StorageReference/i,
      /s3\.putObject/i,
      /BlobServiceClient/i,
    ],
    suggestion: 'Configure storage security rules to restrict access to authenticated users; implement resource ownership verification',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.Informational,
  },
  {
    code: 'FILE012',
    message: 'Executable file extension allowed in upload',
    severity: SecuritySeverity.Error,
    patterns: [
      /\.(?:exe|sh|bat|cmd|ps1|msi|dll|so|bin)\b.*(?:upload|file|allow)/i,
      /(?:upload|file|allow).*\.(?:exe|sh|bat|cmd|ps1|msi|dll|so|bin)\b/i,
    ],
    suggestion: 'Block executable file uploads (.exe, .sh, .bat, .dll, etc.); whitelist only safe file types',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'FILE013',
    message: 'Reminder: Enable access logs for file storage and monitor for anomalies',
    severity: SecuritySeverity.Info,
    patterns: [
      /S3Client/i,
      /new\s+Storage\s*\(/i,
      /BlobServiceClient/i,
      /CloudStorageClient/i,
    ],
    suggestion: 'Enable access logging on storage buckets/containers; monitor for unauthorized access patterns',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.Informational,
  },
  {
    code: 'FILE014',
    message: 'File type validated by extension only, not magic bytes',
    severity: SecuritySeverity.Warning,
    patterns: [
      /\.(?:endsWith|match)\s*\(\s*['"]\.(?:jpg|png|pdf|doc)/i,
      /\.split\s*\(\s*['"]\.['"].*pop/i,
      /path\.extname/i,
    ],
    suggestion: 'Validate file type using magic bytes (file signatures) not just extensions; use libraries like file-type or mmmagic',
    category: SecurityCategory.FileHandling,
    ruleType: RuleType.CodeDetectable,
  },
];
