import { SecurityRule, SecuritySeverity, SecurityCategory, RuleType } from '../types';

export const infrastructureRules: SecurityRule[] = [
  {
    code: 'INFRA001',
    message: 'Reminder: Use separate databases, keys, and configurations for development and production',
    severity: SecuritySeverity.Info,
    patterns: [
      /NODE_ENV/,
      /RAILS_ENV/,
      /DJANGO_SETTINGS/i,
      /APP_ENV/,
    ],
    suggestion: 'Never share databases, API keys, or secrets between development and production environments. Use environment-specific configuration files or environment variables to isolate each environment completely',
    category: SecurityCategory.InfrastructureDeployment,
    ruleType: RuleType.Informational,
  },
  {
    code: 'INFRA002',
    message: 'Debug mode may be enabled in production configuration',
    severity: SecuritySeverity.Warning,
    patterns: [
      /DEBUG\s*[:=]\s*(?:true|1|['"]on['"])/i,
      /FLASK_DEBUG\s*[:=]\s*(?:true|1)/i,
      /APP_DEBUG\s*[:=]\s*(?:true|1)/i,
    ],
    suggestion: 'Ensure debug mode is disabled in production. Debug mode can expose sensitive information, stack traces, and internal application details to attackers',
    category: SecurityCategory.InfrastructureDeployment,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'INFRA003',
    message: 'Verbose or debug logging level may be active in production',
    severity: SecuritySeverity.Warning,
    patterns: [
      /level\s*[:=]\s*['"](?:debug|trace|verbose)['"]/i,
      /LOG_LEVEL\s*[:=]\s*['"](?:debug|trace|verbose)['"]/i,
      /logging\.(?:DEBUG|TRACE)/,
    ],
    suggestion: 'Set logging level to "info", "warn", or "error" in production. Debug/trace/verbose logging can expose sensitive data and degrade performance',
    category: SecurityCategory.InfrastructureDeployment,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'INFRA004',
    message: 'Stack traces may be exposed in production configuration',
    severity: SecuritySeverity.Warning,
    patterns: [
      /showStackTrace\s*[:=]\s*true/i,
      /SHOW_ERRORS\s*[:=]\s*(?:true|1)/i,
      /fullError\s*[:=]\s*true/i,
      /displayErrors\s*[:=]\s*(?:true|1)/i,
    ],
    suggestion: 'Disable stack trace display in production. Stack traces reveal internal paths, library versions, and code structure that help attackers',
    category: SecurityCategory.InfrastructureDeployment,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'INFRA005',
    message: 'Secret may be embedded in Docker image via ENV, ARG, or COPY',
    severity: SecuritySeverity.Error,
    patterns: [
      /(?:ENV|ARG)\s+\w*(?:SECRET|PASSWORD|KEY|TOKEN)\w*/i,
      /COPY\s+.*\.env/i,
      /COPY\s+.*credentials/i,
    ],
    suggestion: 'Never bake secrets into Docker images. Use runtime environment variables, Docker secrets, or a secrets manager to inject credentials at container start',
    category: SecurityCategory.InfrastructureDeployment,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'INFRA006',
    message: 'Reminder: Ensure secrets are not printed in build or CI logs',
    severity: SecuritySeverity.Warning,
    patterns: [
      /echo\s+.*\$\{?\w*(?:SECRET|PASSWORD|KEY|TOKEN)/i,
      /printenv/i,
    ],
    suggestion: 'Mask or suppress secrets in CI/CD output. Use built-in secret masking features in GitHub Actions, GitLab CI, or your CI platform to prevent accidental exposure in build logs',
    category: SecurityCategory.InfrastructureDeployment,
    ruleType: RuleType.Informational,
  },
  {
    code: 'INFRA007',
    message: 'Source maps may be deployed to production',
    severity: SecuritySeverity.Warning,
    patterns: [
      /sourceMappingURL/,
      /devtool\s*:\s*['"].*source-map['"]/i,
      /sourceMap\s*[:=]\s*true/i,
      /generate_source_map\s*[:=]\s*true/i,
    ],
    suggestion: 'Disable source maps in production builds or upload them to a private error tracking service (e.g., Sentry). Source maps expose your original source code to anyone who inspects the browser',
    category: SecurityCategory.InfrastructureDeployment,
    ruleType: RuleType.CodeDetectable,
  },
  {
    code: 'INFRA008',
    message: 'Test, seed, or mock data may be present in production code',
    severity: SecuritySeverity.Warning,
    patterns: [
      /(?:test|seed|mock)(?:_|-)?data/i,
      /faker\./i,
      /(?:test|seed)(?:_|-)?fixture/i,
    ],
    suggestion: 'Remove test data, seed scripts, and mock fixtures from production deployments. Test data can contain weak credentials, bypass security controls, or expose internal structure',
    category: SecurityCategory.InfrastructureDeployment,
    ruleType: RuleType.CodeDetectable,
  },
];
