/**
 * Utility to detect if a file is auto-generated or minified and should be skipped from security analysis.
 * This helps reduce false positives from generated code, build artifacts, and minified bundles.
 */

/**
 * Main function to determine if a file should be skipped from scanning.
 * Checks both file path patterns and content markers.
 */
export function isGeneratedFile(filePath: string, content: string): boolean {
  // Check file path patterns first (faster)
  if (isGeneratedByPath(filePath)) {
    return true;
  }

  // Check file content markers
  if (isGeneratedByContent(content)) {
    return true;
  }

  return false;
}

/**
 * Check if file path matches common patterns for generated files.
 */
function isGeneratedByPath(filePath: string): boolean {
  const normalizedPath = filePath.replace(/\\/g, '/').toLowerCase();

  const generatedPathPatterns = [
    /\/generated\//,
    /\.generated\./,
    /-generated\./,
    /\.min\.js$/,
    /\.min\.css$/,
    /\.bundle\.js$/,
    /\.chunk\.js$/,
    /\/dist\//,
    /\/build\//,
    /\/out\//,
    /\/target\//,
    /\/__generated__\//,
    /\/\.next\//,
    /\/\.nuxt\//,
    /\/vendor\//,
    /\/third.?party\//i,
    /workbox-.*\.js$/,
    /sw\.js$/,
    /service-?worker\.js$/i,
  ];

  return generatedPathPatterns.some(pattern => pattern.test(normalizedPath));
}

/**
 * Check if file content contains markers indicating it's auto-generated.
 */
function isGeneratedByContent(content: string): boolean {
  // Check first 500 characters for generation markers (performance optimization)
  const header = content.substring(0, 500);

  const generationMarkers = [
    /@generated/i,
    /@auto-generated/i,
    /@autogenerated/i,
    /automatically generated/i,
    /do not edit/i,
    /code generator/i,
    /this file is generated/i,
    /generated by \w+/i,
    /GENERATED CODE/i,
    /AUTO-GENERATED/i,

    // GraphQL/Apollo
    /apollo.*codegen/i,
    /graphql.*generator/i,

    // Protobuf
    /protocol buffer compiler/i,
    /protoc.*generated/i,

    // Swagger/OpenAPI
    /swagger.*codegen/i,
    /openapi.*generator/i,

    // TypeScript declaration files
    /typescript.*compiler/i,

    // Build tools
    /webpack/i,
    /rollup/i,
    /parcel/i,
  ];

  if (generationMarkers.some(marker => marker.test(header))) {
    return true;
  }

  // Check for minified code (heuristic)
  if (isMinified(content)) {
    return true;
  }

  return false;
}

/**
 * Heuristic to detect minified code based on line length and patterns.
 */
function isMinified(content: string): boolean {
  // Sample first 1000 characters for performance
  const sample = content.substring(0, 1000);

  // Count newlines to calculate average line length
  const newlineCount = (sample.match(/\n/g) || []).length;

  // Avoid division by zero
  if (newlineCount === 0) {
    // If there are no newlines in 1000 chars, it's likely minified
    return sample.length > 500;
  }

  const avgLineLength = sample.length / (newlineCount + 1);

  // If average line length > 300, likely minified
  if (avgLineLength > 300) {
    return true;
  }

  // Check for common minification patterns
  const minifiedPatterns = [
    /;[a-z]=function\(/,  // Minified function assignments
    /\}\([a-z0-9,]{10,}\)/,  // IIFE with many single-char args
    /var [a-z]=[a-z],/,  // Single-letter variables in sequence
  ];

  return minifiedPatterns.some(pattern => pattern.test(sample));
}
